name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the pipeline on

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 381491999801.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          docker build -t final-test-api .
          docker tag final-test-api:latest 381491999801.dkr.ecr.us-east-1.amazonaws.com/final-test-api:latest
          docker push 381491999801.dkr.ecr.us-east-1.amazonaws.com/final-test-api:latest
